export const FetchAllClients = () => {
	const clientArray = [
		{
			companyName: 'companyname1',
			clientName: 'client name1',
			address: 'address1',
			city: 'city1',
			zipCode: 'zipcode1',
			country: 'country1',
		},
		{
			companyName: 'companyname2',
			clientName: 'client name2',
			address: 'address2',
			city: 'city2',
			zipCode: 'zipcode2',
			country: 'country2',
		},
		{
			companyName: 'companyname3',
			clientName: 'client name3',
			address: 'address3',
			city: 'city3',
			zipCode: 'zipcode3',
			country: 'country3',
		},
		{
			companyName: 'companyname4',
			clientName: 'client name4',
			address: 'address4',
			city: 'city4',
			zipCode: 'zipcode4',
			country: 'country4',
		},
		{
			companyName: 'companyname5',
			clientName: 'client name5',
			address: 'address5',
			city: 'city5',
			zipCode: 'zipcode5',
			country: 'country5',
		},
		{
			companyName: 'companyname6',
			clientName: 'client name6',
			address: 'address6',
			city: 'city6',
			zipCode: 'zipcode6',
			country: 'country6',
		},
		{
			companyName: 'companyname7',
			clientName: 'client name7',
			address: 'address7',
			city: 'city7',
			zipCode: 'zipcode7',
			country: 'country7',
		},
		{
			companyName: 'companyname8',
			clientName: 'client name8',
			address: 'address8',
			city: 'city8',
			zipCode: 'zipcode8',
			country: 'country8',
		},
		{
			companyName: 'companyname9',
			clientName: 'client name9',
			address: 'address9',
			city: 'city9',
			zipCode: 'zipcode9',
			country: 'country9',
		},
		{
			companyName: 'companyname10',
			clientName: 'client name10',
			address: 'address10',
			city: 'city10',
			zipCode: 'zipcode10',
			country: 'country10',
		},
	];

	return clientArray;
};
